---
- name: Install MongoDB 4.4 on Linux Mint 21.1
  hosts: all
  become: yes

  tasks:
    - name: Add MongoDB repository
      apt_repository:
        repo: deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
        state: present
        update_cache: yes

    - name: Install MongoDB packages
      apt:
        name: mongodb-org
        state: latest

    - name: Start MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes

