---
- name: Install MongoDB
  hosts: group_name
  become: true

  tasks:
    - name: Add MongoDB GPG Key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.4.asc
        state: present

    - name: Add MongoDB repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse 
        state: present

    - name: Install MongoDB packages
      apt:
        name: mongodb-org
        state: present
        update_cache: yes



...
